pipeline{
    agent {
      node {
        label 'slave1'
      }
    }

    tools {
         maven 'MAVEN_HOME'
         jdk 'JAVA_HOME'
    }

    stages {
      stage('pre-build step') {
            steps {
		sh '''
                echo "Pre Build Step"
		'''
	    }
	}
       stage('Git Checkout'){
            steps{
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'github access', url: 'https://github.com/HimachalamP/AWS-DevOps-Project.git']]])
            }
        }
        stage('build'){
            steps{
               sh '''
                mvn package
	        	cp -r ${WORKSPACE}/target/simple-maven-project-1.0-SNAPSHOT.war ${WORKSPACE}/Projects/Docker-Kubernetes/webapp.war
                '''
            }
        }
        stage ('Unit Test') {
	        steps {
                echo 'Running Unit Testing'
                sh '''
                mvn test
                '''
             }
         }
         stage ('Update Local Repository') {
                steps {
                  echo 'Update m2 repository'
                  sh '''
                  mvn install
                  '''
             }
         }
         stage ('Docker Build') {
                 steps {
                    script {
                      sh "docker build -t himachalamp/webapp-app-tomcat:latest -f Projects/Docker-Kubernetes/Dockerfile ."
                     }
                    } 
                }
                stage ('Docker Push') {
                 steps{
                        sh ''' 
			  docker push himachalamp/webapp-app-tomcat:latest
	                '''
                     }      
               }
          stage('Kubernetes Deployment') {
            parallel {
              stage('Kubernetes Dev') {
                 when {
                   expression { "$Env_Name" == 'dev-ns' }
                 }
                  steps{
                      echo "Deployment in Dev Environment"
                      sh '''
                        kubectl apply -f  Projects/Docker-Kubernetes/DEV/deployment.yaml -n "$Env_Name"
                        sleep 10
		                kubectl apply -f Projects/Docker-Kubernetes/DEV/service.yaml -n "$Env_Name"
		                sleep 20
		                kubectl apply -f Projects/Docker-Kubernetes/DEV/ingress.yaml -n "$Env_Name"
                      '''
                   }
                }
             stage('Kubernetes SBOX'){
               when {
                 expression { "$Env_Name" == 'sbox-ns' }
               }
               steps {
                   echo "Deployment in SBOX Environment"
                      sh '''
                        kubectl apply -f  Projects/Docker-Kubernetes/SBOX/deployment.yaml -n "$Env_Name"
                        sleep 10
		                kubectl apply -f Projects/Docker-Kubernetes/SBOX/service.yaml -n "$Env_Name"
	                    sleep 20
		                kubectl apply -f Projects/Docker-Kubernetes/SBOX/ingress.yaml -n "$Env_Name"
                    '''
                  }
                }
             stage('Kubernetes Prod '){
               when {
                 expression { "$Env_Name" == 'prod-ns' }
               }
               steps {
                   echo "Deployment in Prod Environment"
                     sh '''
                        kubectl apply -f  Projects/Docker-Kubernetes/PROD/deployment.yaml -n "$Env_Name"
                        sleep 10
		                kubectl apply -f Projects/Docker-Kubernetes/PROD/service.yaml -n "$Env_Name"
				  	    sleep 20
		                kubectl apply -f Projects/Docker-Kubernetes/PROD/ingress.yaml -n "$Env_Name"
                      '''
                  }
                }
            }
          }
         stage (' Deployment Validation') {
	        steps {
                sh '''
                  sleep 10
                   kubectl get all -n "$Env_Name"
				   kubectl get ingress -n "$Env_Name"
                 '''
             }
         }
       stage('post-build step') {
            steps {
		sh '''
                echo "Successfull Pipeline"
		'''
	    }
	}
     }
}
